spring.application.name=OrderService

server.port=8087

spring.datasource.url=jdbc:mysql://localhost:3306/spring_boot_cloud_training
spring.datasource.username=root
spring.datasource.password=0000

#dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#ddl
spring.jpa.hibernate.ddl-auto=create

server.error.include-exception=true
server.error.include-message=always