spring: 
  application: 
    name: movie-ticket-validator
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    #bootstrap-servers: 52.73.233.11:9092
    producer:
      #key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      
movie:
   tickets: 
     topic: '${MOVIEW_TICKETS_PRODUCER_TOPIC:movie-tickets}'
     partitions: '${MOVIE_TICKETS_TOPIC_PARTITIONS:3}'
     
server: 
  port: 5002