spring.application.name=SpringBoot2ActuatorTest


#Actuator Endpoints Exposing
management.endpoints.web.exposure.include=*

#management.endpoints.web.exposure.include=beans,env,health

#management.endpoints.web.exposure.exclude=beans,env,health


#Setup app base path for actuator
#management.endpoints.web.base-path=/myapp


#management.endpoint.health.show-details=when-authorized
management.endpoint.health.show-details=always

#management.endpoint.health.roles=ADMIN,EMPLOYEE

#management.endpoint.health.enabled=false

### Now from Spring boot version 3, by default the value of all properties are hidden. ********

###  To display the value in /env endpoint, below configuration needs to be added in application.properties file.
#management.endpoint.env.show-values=ALWAYS

#management.endpoint.configprops.show-values=ALWAYS


spring.mvc.view.prefix=sample
spring.mvc.view.suffix=test

### METADATA OF PROJECT ###
info.my.app.id=100
info.my.app.title=ZAYYNI-APP
info.my.app.vendor=ZAYYNI-LHR

#http://localhost:8080/actuator

#http://localhost:8080/actuator/health

#http://localhost:8080/actuator/info

#http://localhost:8080/actuator/beans

#http://localhost:8080/actuator/env

#http://localhost:8080/actuator/configprops

#http://localhost:8080/actuator/mappings

#http://localhost:8080/actuator/scheduledtasks
