spring.application.name=SpringBoot2ActuatorTest


#Actuator Endpoints Exposing
management.endpoints.web.exposure.include=*

#management.endpoints.web.exposure.include=beans,env,health

#management.endpoints.web.exposure.exclude=beans,env,health


#Setup app base path for actuator
#management.endpoints.web.base-path=/myapp
