spring.application.name=SpringCloudCSEmployeeApp


server.port=9900

eureka.client.service-url.defaultZone=http://localhost:8761/eureka


#Acuator Refresh connection
management.endpoints.web.exposure.include=*

#
#Below is the url to hit to get the latest changes from the config server
#http://localhost:9900/actuator/refresh